server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://ec2-3-225-213-67.compute-1.amazonaws.com:5432/d83m9uc17b9tdm
    username: oixvrzjpwlsije
    password: 0617758846cdab6b395a592ff6824bf92e6c3263ca3132fa38bedcd0db4ea18c
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ganifaturrozak11@gmail.com
    password: wvsxzzkvpmlpiazp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
